name: sleek_circular_slider_cheebeez
description: A highly customizable circular slider/progress bar & spinner for Flutter. This is a community-maintained fork of the original sleek_circular_slider.
version: 1.0.0
homepage: https://github.com/cheebeez/sleek_circular_slider
repository: https://github.com/cheebeez/sleek_circular_slider

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: