name: sleek_circular_slider
description: A highly customizable circular slider/progress bar & spinner for Flutter.
version: 2.1.0
homepage: https://github.com/matthewfx/sleek-circular-slider

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
